---
window:
  width: 768
  height: 512
  tile_size: 64
  cursor_size: 48
  default_mode: :seed
  bg_color: 0xff_4d4331
  pause_color: 0x80_c0c0c0
  start_coins: 50
crop:
  quality:
    initial: $(40..60)
    hoe: 2
    can: 5
    wither_threshold: 30
    debug: false
    # wither_chance: $70 + self.quality
  special_states:
    sown: 0,
    ripe: -5,
    harvested: -4,
    dead: -3,
    water: -2,
    soil: -1
  reward:
    base: 10
    quality: 50
hud:
  action_cost:
    hoe:   3,
    can:   1,
    seed: 10,
    grab:  0,
    trash: 2
  small_font_size: 20
  big_font_size: 40
  pos_in_tileset:
    hoe: 1,
    can: 2,
    seed: 3,
    grab: 4,
    trash: 5
